
DROP TABLE IF EXISTS Leiripaikka CASCADE;
DROP TABLE IF EXISTS Leiri CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Hakemus CASCADE;
DROP TABLE IF EXISTS Leiriohjaajuus CASCADE;